apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge
  labels:
    app: tech-challenge
spec:
  template:
    metadata:
      name: tech-challenge
      labels:
        app: tech-challenge
    spec:
      containers:
        - name: tech-challenge-api
          image: 1811183/tech-challenge:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secret
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secret
                  key: spring.datasource.password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secret
                  key: spring.datasource.username
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge